# **Twitter Scraping with Tweepy**

There are a few different methods to scrape tweets, all were experimented with and Tweepy was found to be the best for our use case, as it can fetch tweets containing specific keywords, using its ***Cursor class***

In [ ]:
import pandas as pd

In [ ]:
import re
import tweepy
from tweepy import OAuthHandler
from textblob import TextBlob


Twitter Developers account is required to get the following Tokens -

In [ ]:
consumer_key = ''
consumer_secret = ''
access_token = ''
access_token_secret = ''

1. Set access token and secret
2. Create tweepy API object to fetch tweets

In [ ]:
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

**Queries like this can be created to specify the keywords or phrases we want in our Tweets**

One single string is consider 1 Query, and a single query can have multiple OR seperated words and phrases, and we can even exclude certain words/phrases by - sign. OR works in this way; if I say (problem) OR (issue), it will give me tweets containing both or either of these two words. If I simply define two different queries, I may get same repeated tweets. We can pass a List of many Queries at once in the following way-

In [ ]:
q = ['(@YESBANK complain) OR (@YESBANK problem) OR (@YESBANK issue) OR (@YESBANK trouble) OR (@YESBANK inconvinience) -thanks -(thank you) ',
               '(@TheOfficialSBI complain) OR (@TheOfficialSBI problem) OR (@TheOfficialSBI issue) OR (@TheOfficialSBI trouble) OR (@TheOfficialSBI inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@ICICIBank_Care complain) OR (@ICICIBank_Care problem) OR (@ICICIBank_Care issue) OR (@ICICIBank_Care trouble) OR (@ICICIBank_Care inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)'
              '(@financialombuds complain) OR (@financialombuds problem) OR (@financialombuds issue) OR (@financialombuds trouble) OR (@financialombuds inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
              '(@GooglePayIndia complain) OR (@GooglePayIndia problem) OR (@GooglePayIndia issue) OR (@GooglePayIndia trouble) OR (@GooglePayIndia inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@bankofbaroda problem) OR (@bankofbaroda issue) OR (@bankofbaroda trouble) OR (@bankofbaroda inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@MyIndusIndBank complain) OR (@MyIndusIndBank problem) OR (@MyIndusIndBank issue) OR (@MyIndusIndBank trouble) OR (@MyIndusIndBank inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@pnbindia complain) OR (@pnbindia problem) OR (@pnbindia issue) OR (@pnbindia trouble) OR (@pnbindia inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@HDFCBank_Cares complain) OR (@HDFCBank_Cares problem) OR (@HDFCBank_Cares issue) OR (@HDFCBank_Cares trouble) OR (@HDFCBank_Cares inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@FinMinIndia complain) OR (@FinMinIndia problem) OR (@FinMinIndia issue) OR (@FinMinIndia trouble) OR (@FinMinIndia inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@RBI complain) OR (@RBI problem) OR (@RBI issue) OR (@RBI trouble) OR (@RBI inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@RBIsays complain) OR (@RBIsays problem) OR (@RBIsays issue) OR (@RBIsays trouble) OR (@RBIsays inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@PhonePeSupport complain) OR (@PhonePeSupport problem) OR (@PhonePeSupport issue) OR (@PhonePeSupport trouble) OR (@PhonePeSupport inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
               '(@Paytmcare complain) OR (@Paytmcare problem) OR (@Paytmcare issue) OR (@Paytmcare trouble) OR (@Paytmcare inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
              '(@AmazonHelp pay upi complain) OR (@AmazonHelp pay upi problem) OR (@AmazonHelp pay upi issue) OR (@AmazonHelp pay upi trouble) OR (@AmazonHelp pay upi inconvinience) -thanks -(thank you) -(issue resolved) -(matter resolved)',
              '#rbicomplaint',
              ]

I made a lot of different queries to get more and more relevant tweets while avoiding repetition

In [ ]:
qqq = ['bank complaint please resolve', 'bank complain please resolve','atm complaint please resolve','transaction complaint please resolve','atm complain please resolve','transaction complain please resolve'

,'bank complaint please reply', 'bank complain please reply','atm complaint please reply','transaction complaint please reply','atm complain please reply','transaction complain please reply'

,'bank complaint no help', 'bank complain no help','atm complaint no help','transaction complaint no help','atm complain no help','transaction complain no help','bank complaint no reply', 'bank complain no reply','atm complaint no reply','transaction complaint no reply','atm complain no reply','transaction complain no reply']

In [ ]:
qqq2 = ['debit card complain please resolve', 'debit card complain please reply' ,'debit card complain no help','debit card complain no help']

I ended up not using the following clean tweets function and simply got the raw tweets as they some times had more information in the form Emojis etc. which could help in annotation

In [ ]:
def clean_tweet(tweet):
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ",tweet).split())

In [ ]:
q2 = ['@ICICIBank_Care credit card' ,
       '@HDFCBank_Cares credit card', '@AskCiti credit card', '@BofA_Help credit card'
      '@RBS_Help credit card', '@BarclaysUKHelp credit card']

### **The Twitter scraping process begins here.** 

Now that we have our Queries list, we can iterate over each query and fetch tweets using ***tweepy.Cursor()***, as given below. The ***items()*** method specifies how many maximum tweets we want for that particular query. We create a list which stores the fetched tweets as strings. We can also excluded Retweets and tweets with any other text that we want by ***if not in***

In [ ]:
lis3 = []
for i in qqq2:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis3.append(tweet.full_text)

**Then we just store this list as a pandas Dataframe, and later we can combine all dataframes into one single CSV**

In [ ]:
df3 = pd.DataFrame(lis3, columns = ['Complaint'])
df3.to_csv('debit.csv')

In [ ]:
df3

                                           Complaint
0  Hello @SBICard_Connect,\nHere's to complain ab...

Different queries were defined to get tweets regarding different domains of Finance, and in order to keep a record of the specific topic of the tweet, they were saved in different CSV files then the Topic of those tweets were manually added inside the collated CSV.

## **Experiments with All Queries**

In [ ]:
qqq = ['bank complaint please resolve', 'bank complain please resolve','atm complaint please resolve','transaction complaint please resolve','atm complain please resolve','transaction complain please resolve']

In [ ]:
def clean_tweet(tweet):
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ",tweet).split())

In [ ]:
q2 = ['@ICICIBank_Care credit card' ,
       '@HDFCBank_Cares credit card', '@AskCiti credit card', '@BofA_Help credit card'
      '@RBS_Help credit card', '@BarclaysUKHelp credit card']

In [ ]:
lis3 = []
for i in qqq:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis3.append(tweet.full_text)

In [ ]:
df3 = pd.DataFrame(lis3, columns = ['Complaint'])
df3.to_csv('bnks.csv')

In [ ]:
df3

                                            Complaint
0   @ICICIBank No resolution till date for unlawfu...
1   @HDFC_Bank @HDFC_Bank \nPlease resolve my quer...
2   @HDFC_Bank \nPlease resolve my query\nComplain...
3   @LivBank Please know that I am yet to see a ba...
4   @RBI @rblbank @FinMinIndia @ChairmanIba RBL Ba...
5   @HDFCBank_Cares I'm tired and sick of complain...
6   @myaccessbank @SaintDav3 I withdraw from stanb...
7   @myaccessbank I withdraw from stanbic at iju i...
8   @myaccessbank @thintalltiti I withdraw from st...
9   @myaccessbank I withdraw from stanbic at iju i...
10  @access_more @myaccessbank @coronationinsur I ...
11  @myaccessbank I withdraw from stanbic at iju i...
12  @myaccessbank I withdraw from stanbic at iju i...
13  @myaccessbank I withdraw from stanbic at iju i...
14  @myaccessbank I withdraw from stanbic at iju i...
15  @accessbank_help I withdraw from stanbic at ij...
16  @accessbank_help I withdraw from stanbic at ij...
17  @accessbank_help @TaiwoAjibise I withdraw from...
18  @myaccessbank I withdraw from stanbic at iju i...
19  @myaccessbank I withdraw from stanbic at iju i...
20  @access_more @myaccessbank I withdraw from sta...
21  @myaccessbank @Abimbola3969 I withdraw from st...
22  @access_more @myaccessbank I withdraw from sta...
23  @access_more @myaccessbank Good afternoon,I wi...
24  @Widsey3 Hi Widsey. We'll make every effort to...
25  Hello @SBICard_Connect,\nHere's to complain ab...
26  @MyFCMB\nGood morning, please how long does it...
27  @fcmb_help\nGood morning, please how long does...

In [ ]:
qq2 = ['@ICICIBank_Care debit card' ,
       '@HDFCBank_Cares debit card', '@AskCiti debit card', '@BofA_Help debit card'
      '@RBS_Help debit card', '@BarclaysUKHelp debit card', '@Ask_WellsFargo debit card']

In [ ]:
lis4 = []
for i in qq2:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(100):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis4.append(tweet.full_text)

In [ ]:
df4 = pd.DataFrame(lis4, columns = ['Complaint'])
df4.to_csv('debitcards.csv')

In [ ]:
df4

                                             Complaint
0    @ICICIBank_Care can i pay @ICICIBank_Care cred...
1    @ICICIBank_Care i have been charged an annual ...
2    Hey @ICICIBank @ICICIBank_Care, \nKis baat ke ...
3    @ICICIPruMF pathetic pathetic service really, ...
4    @ICICIBank_Care started to cheating  own custo...
..                                                 ...
119  @Ask_WellsFargo Why am I waiting 60mins just s...
120  @WellsFargo @Ask_WellsFargo I find it interest...
121  @Ask_WellsFargo @LAKings I received a disturbi...
122  @bihbongha My daughters debit card got “found”...
123  @WellsFargo @Ask_WellsFargo are you still open...

[124 rows x 1 columns]

In [ ]:
qqq2 = ['@ICICIBank_Care netbanking' ,
       '@HDFCBank_Cares netbanking', '@AskCiti netbanking', '@BofA_Help netbanking'
      '@RBS_Help netbanking', '@BarclaysUKHelp netbanking', '@Ask_WellsFargo netbanking', '@ChaseSupport']

In [ ]:
lis5 = []
for i in qqq2:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(100):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis5.append(tweet.full_text)

In [ ]:
df5 = pd.DataFrame(lis5, columns = ['Complaint'])
df5.to_csv('netbankingcards.csv')

In [ ]:
df5

                                            Complaint
0   @ICICIBank_Care cannot login to netbanking for...
1   @lClClBankcare2 @ICICIBank_Care @ICICIBank  Wh...
2   @ICICIBank_Care @ICICIBank_Care @ICICIBank Thi...
3   @ICICIBank @ICICIBank_Care I am not able to us...
4   @ICICIBank_Care facing issue with login on ici...
5   @ICICIBank_Care Hi, since morning i have been ...
6   @ICICIBank_Care Hi, I already have your credit...
7   Dear @ICICIBank_Care do you have Re-kyc updati...
8   @ICICIBank @ICICIBank_Care All transactions fo...
9   Don't know what so say\nSince long time trying...
10  What the hell is wrong with your netbanking an...
11  @ICICIBank_Care @ICICIBank_Care Customer care ...
12  @manishbhoola @ICICIBank @ICICIBank_Care @RBI ...
13  @HDFC_Bank @HDFCBank_Cares I had requested to ...
14  @HDFCBank_Cares Why there is no 2 factor authe...
15  @HDFCBank_Cares \nI want to change my email ID...
16  @HDFC_Bank @HDFCBank_Cares It’s almost over a ...
17  @HDFCBank_Cares @HDFC_Bank Amount got deducted...
18  @HDFCBank_Cares Hi, I have opened my salary ba...
19  @HDFC_Bank @HDFCBank_Cares NetBanking site is ...
20  @HDFCBank_Cares dear team\nWhat the hell is th...
21  Got thr following sms. #Phishing attempt. DONT...
22  Without doubt @HDFC_Bank has one of the worst ...
23  How do we reach customer care of HDFC Bank.. N...
24  @HDFCBank_Cares @HDFC_Bank\nI have 2 savings a...
25  @HDFCBank_Cares Hello Sir I have not recieved ...
26  @HDFCBank_Cares My account is showing as a sta...
27  @HDFCBank_Cares How do I check the history of ...
28  @HDFC_Bank \nKindly inform me that these are o...
29  @HDFCBank_Cares\nI'm trying to unlock my net b...
30  @HDFCBank_Cares NetBanking, the Reference numb...
31  @HDFCBank_Cares Why your NetBanking is not wor...
32  @HDFC_Bank @HDFCBank_Cares 😂😂😂 Are you guys hi...
33  @HDFCBank_Cares Netbanking… however go resolve...
34  @onlyequities @HDFCBank_Cares HDFC sirf largec...
35  @HDFCBank_Cares First, for some reason just ge...
36  @HDFCBank_Cares I am unable to reset my netban...
37  @HDFCBank_Cares @HDFC_Bank I am being offered ...
38  @HDFCBank_Cares Hello HDFC, can I change my re...
39  @HDFCBank_Cares Dear HDFC, atleast read the cu...

In [ ]:
qqq3 = ['@ICICIBank_Care atm' ,
       '@HDFCBank_Cares atm', '@AskCiti atm', '@BofA_Help atm'
      '@RBS_Help atm', '@BarclaysUKHelp atm', '@Ask_WellsFargo atm', '@ChaseSupport atm', '@AskUSBank']

In [ ]:
lis6 = []
for i in qqq3:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis6.append(tweet.full_text)

In [ ]:
df6 = pd.DataFrame(lis6, columns = ['Complaint'])
df6.to_csv('atm.csv')

In [ ]:
df6

                                            Complaint
0   Just deposited cash in deposit machine at icic...
1   @ICICIBank_Care But I want to know that where ...
2   cheating by blue dark courier delivery boy ICI...
3   @ICICIBank_Care  Your branch at Maldah Busines...
4   आलू सोना वाला पुराना हो गया - अब मार्केट में ए...
..                                                ...
85  @ChaseSupport I'm an unhappy customer.  I made...
86  Hey @ChaseSupport your atm just ate $500+ of a...
87  @ChaseSupport I understand. Perhaps we can con...
88  @ChaseSupport @Chase your branch at 20871 N Sc...
89  @ChaseSupport why are atms closed at night in ...

[90 rows x 1 columns]

In [ ]:
qqq4 = ['@ICICIBank_Care loan' ,
       '@HDFCBank_Cares loan', '@AskCiti loan', '@BofA_Help loan'
      '@RBS_Help loan', '@BarclaysUKHelp loan', '@Ask_WellsFargo loan', '@ChaseSupport loan', '@AskUSBank loan']

In [ ]:
lis7 = []
for i in qqq4:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis7.append(tweet.full_text)

In [ ]:
df7 = pd.DataFrame(lis7, columns = ['Complaint'])
df7.to_csv('loan.csv')

In [ ]:
df7

                                             Complaint
0    @ICICIBank_Care I m trying to cancel my person...
1    @ICICIBank_Care @hdfc @IDBI_Bank @AxisBank I w...
2    @ICICIBank_Care @PMOIndia @RBI @aajtak @CourtI...
3    @ICICIBank_Care Since the day I chose ICICI I ...
4    @ICICIBank_Care I am a Customer with a 20 uear...
..                                                 ...
321  @BarclaysUKHelp I need urgent assistance that ...
322  @Ask_WellsFargo Why does Wells Fargo remove a ...
323  Hey @Chase @ChaseSupport  this has been a grea...
324  @ChaseSupport Trust me, I’ve exhausted all way...
325  @ChaseSupport i applied for a chase loan Monda...

[326 rows x 1 columns]

In [ ]:
qqq5 = ['@ICICIBank_Care transaction' ,
       '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
      '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']
# ['(@YESBANK transaction fail',
#                '(@TheOfficialSBI transaction fail',
#                '(@ICICIBank_Care transaction fail',   '@financialombuds transaction fail', '@GooglePayIndia transaction fail',
#                '@bankofbaroda transaction fail',
#                '@MyIndusIndBank transaction fail',
#                '@pnbindia transaction fail',
#                '@HDFCBank_Cares transaction fail',
               
#                '@RBIsays transaction fail',
#                '@PhonePeSupport transaction fail',
#                '@Paytmcare transaction fail',
#               '@AmazonHelp transaction fail',
#               '@AskCiti transaction fail', '@BofA_Help transaction fail'
#       '@RBS_Help transaction fail', '@BarclaysUKHelp transaction fail', 
#  '@Ask_WellsFargo transaction fail', '@ChaseSupport transaction fail', '@AskUSBank transaction fail']

In [ ]:
lis8 = []
for i in qqq5:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis8.append(tweet.full_text)

In [ ]:
df8 = pd.DataFrame(lis8, columns = ['Complaint'])
df8.to_csv('transaction.csv')

In [ ]:
df8

                                             Complaint
0    @ICICIBank_Care This is something very serious...
1    @RBI @ICICIBank_Care @ICICIBank @CRED_support ...
2    Fraud transaction through CRED for SBI C-Card ...
3    @DBSBankIndia I am new DBS customer. I really ...
4    @CapitalFloat @ICICIBank @ICICIBank_Care I alr...
..                                                 ...
213  @ChaseSupport I need to get a transaction canc...
214  @Chase @ChaseSupport trying to do banking tran...
215  @Chase @ChaseSupport \n\nLogging onto my accou...
216  I tried to reach a Chase representative to rep...
217  @ChaseSupport @ChaseSupport straight confirmed...

[218 rows x 1 columns]

In [ ]:
qqq7 = ['@YESBANK bad customer service',
               '@TheOfficialSBI bad customer service',
               '@ICICIBank_Care bad customer service',   '@financialombuds bad customer service', '@GooglePayIndia bad customer service',
               '@bankofbaroda bad customer service',
               '@MyIndusIndBank bad customer service',
               '@pnbindia bad customer service',
               '@HDFCBank_Cares bad customer service',
               '@RBIsays bad customer service',
               '@PhonePeSupport bad customer service',
               '@Paytmcare bad customer service',
              '@AmazonHelp bad customer service',
              '@AskCiti bad customer service', '@BofA_Help bad customer service'
      '@RBS_Help bad customer service', '@BarclaysUKHelp bad customer service', 
 '@Ask_WellsFargo bad customer service', '@ChaseSupport bad customer service', '@AskUSBank bad customer service']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis9 = []
for i in qqq7:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis9.append(tweet.full_text)

In [ ]:
df9 = pd.DataFrame(lis9, columns = ['Complaint'])
df9.to_csv('customerserv.csv')

In [ ]:
df9

                                            Complaint
0   @YESBANK Such a very bad service by your bank ...
1   @TheOfficialSBI Your service is curse to entir...
2   Dear @TheOfficialSBI Your Reotipur Branch Code...
3   Terrible experience at the @TheOfficialSBI bra...
4   @ICICIBank @ICICIBank_Care why do you have hef...
5   @ICICIBank_Care @ICICIPruLife Such a bad custo...
6   @ICICIBank_Care Dear icici your service is ver...
7   @ICICIBank_Care \nTweeted my issue,even sent t...
8   @ICICIBank_Care Very bad service I calling cus...
9   @ICICIBank_Care very bad service customer not ...
10  I requested Google pay customer support to ple...
11  I have never seen such a bad bank like @bankof...
12  @MyIndusIndBank very bad customer service of I...
13  @MyIndusIndBank This very bad Customer service...
14  @BankIndusind @MyIndusIndBank @Indusindbank2 @...
15  @MyIndusIndBank \nReally Very Poor Customer Se...
16  @HDFCBank_Cares Hii hdfc I don't want to say s...
17  @HDFC_Bank @HDFCBank_Cares \nSince the credit ...
18  my account is 18month old and well maintain bu...
19  @IDFCFIRSTBank     Please all customers  not o...
20  @suchetadalal @gaddamrajareddy @Bajaj_Finance ...
21  @Paytmcare I can't reedem my fixed deposit amo...
22  I have ordered gas cylinder on 23rd December b...
23  @Vjangid143 @paytmmallcare @Paytmcare @Paytmca...
24  @Paytm @Paytmcare The worst service ever. I m ...
25  @AmazonHelp Had spoken to customer service but...
26  @amazonIN @AmazonHelp VERY BAD CUSTOMER SERVIC...
27  @AmazonHelp @bigbasketblog And I have spoken t...
28  Very bad customer service. Supervisor closed t...
29  @AmazonHelp hi a customer rep on Amazon chat h...
30  @AmazonHelp I’m not sure. My account was from ...
31  @AmazonHelp Many time i called to customer car...
32  @AmazonHelp I have spoken to 5 of your staff m...
33  @AmazonHelp Bery Bad Experience... @amazonIN h...
34  I am utterly disappointed with the poor custom...
35  @AmazonHelp No i am facing issue with link… an...
36  @AmazonHelp but yes i will for sure make aware...
37  @AmazonHelp the food service and customer reso...
38  @AmazonHelp See tht is d problem, you do not g...
39  Just experienced the epitome of bad customer s...
40  @AskCiti still awaiting your valuable response...
41  @Ask_WellsFargo Good luck. Support in under se...
42  @Ask_WellsFargo Good luck. Support in under se...

In [ ]:
qqq8 = ['@ICICIBank_Care mortgage' ,
       '@HDFCBank_Cares mortgage', '@AskCiti mortgage', '@BofA_Help mortgage'
      '@RBS_Help mortgage', '@BarclaysUKHelp mortgage', '@Ask_WellsFargo mortgage', '@ChaseSupport mortgage', '@AskUSBank mortgage']

In [ ]:
lis10 = []
for i in qqq8:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis10.append(tweet.full_text)

In [ ]:
df10 = pd.DataFrame(lis10, columns = ['Complaint'])
df10.to_csv('mortgage.csv')

In [ ]:
df10

                                           Complaint
0  Attention!I recently transferred my OD limit a...
1  BEWARE! If you take out a Citi Card @Citi @Ask...
2  I am doing mortgage with Citi. Today is litera...
3  @BarclaysUKHelp need help. Have mortgage and c...
4  @BarclaysUKHelp So basically you’re not puttin...
5  @BarclaysUKHelp Hi I need to request a Certifi...
6  @BarclaysUKHelp Afternoon. We would like to po...
7  @Ask_WellsFargo Logged in to my account today ...
8  @Ask_WellsFargo I continue to receive emails f...
9  @ChaseSupport what should have been an incredi...

In [ ]:
qqq9 = ['@YESBANK terrible customer service',
               '@TheOfficialSBI terrible customer service',
               '@ICICIBank_Care terrible customer service',   '@financialombuds terrible customer service', '@GooglePayIndia terrible customer service',
               '@bankofbaroda terrible customer service',
               '@MyIndusIndBank terrible customer service',
               '@pnbindia terrible customer service',
               '@HDFCBank_Cares terrible customer service',
               '@RBIsays terrible customer service',
               '@PhonePeSupport terrible customer service',
               '@Paytmcare terrible customer service',
              '@AmazonHelp terrible customer service',
              '@AskCiti terrible customer service', '@BofA_Help terrible customer service'
      '@RBS_Help terrible customer service', '@BarclaysUKHelp terrible customer service', 
 '@Ask_WellsFargo terrible customer service', '@ChaseSupport terrible customer service', '@AskUSBank terrible customer service']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis10 = []
for i in qqq9:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis10.append(tweet.full_text)

In [ ]:
df10 = pd.DataFrame(lis10, columns = ['Complaint'])
df10.to_csv('customerserv2.csv')

In [ ]:
df10

                                            Complaint
0   @YESBANK How much time do you need to respond ...
1   @YESBANK You're such a terrible customer servi...
2   @YESBANK I've not receive any call and resolut...
3   @YESBANK How much time it will take to resolve...
4   Terrible experience at the @TheOfficialSBI bra...
5                 @pnbindia Terrible customer service
6   @AmazonHelp I had returned a product in the ex...
7   @AmazonHelp you canceled an order that I made ...
8   @AmazonHelp Where does this help? Terrible cus...
9   @AmazonUK @AmazonHelp I will continue everyday...
10  @AmazonHelp Your support is terrible. Locked o...
11  @AmazonHelp I ordered for guaranteed delivery ...
12  @AmazonHelp Stop lying and stealing from custo...
13  @AmazonHelp @Jacob_MvPR Absolutely terrible cu...
14  @AmazonHelp @JeffBezos your customer service i...
15  @AmazonHelp I’ve already been through online c...
16  @AmazonHelp Kali, can you read?\n\nI have spen...
17  @AmazonHelp Already contacted customer service...
18  @AmazonHelp Your customer service team is terr...
19  @AmazonHelp I would rather you tell me that yo...
20             @AmazonHelp Terrible customer service.
21  @ChaseSupport \nMy account is locked because o...
22  @ChaseSupport \nMy private banking accounts ar...
23  @ChaseSupport really? Still silence from y’all...
24  @ChaseSupport I just need refund and stop char...
25  Terrible customer service experience with \n@C...

In [ ]:
qqq10 = ['@AskPayPal complaint','@AskPayPal failure', '@AskPayPal failed', '@AskPayPal terrible', '@AskPayPal horrible', '@AskPayPal bad', '@AskPayPal wrong']

In [ ]:
qqq10 = ['@YESBANK horrible customer service',
               '@TheOfficialSBI horrible customer service',
               '@ICICIBank_Care horrible customer service',   '@financialombuds horrible customer service', '@GooglePayIndia horrible customer service',
               '@bankofbaroda horrible customer service',
               '@MyIndusIndBank horrible customer service',
               '@pnbindia horrible customer service',
               '@HDFCBank_Cares horrible customer service',
               '@RBIsays horrible customer service',
               '@PhonePeSupport horrible customer service',
               '@Paytmcare horrible customer service',
              '@AmazonHelp horrible customer service',
              '@AskCiti horrible customer service', '@BofA_Help horrible customer service'
      '@RBS_Help horrible customer service', '@BarclaysUKHelp horrible customer service', 
 '@Ask_WellsFargo horrible customer service', '@ChaseSupport horrible customer service', '@AskUSBank horrible customer service']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis11 = []
for i in qqq10:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis11.append(tweet.full_text)

In [ ]:
df11 = pd.DataFrame(lis11, columns = ['Complaint'])
df11.to_csv('paypal.csv')

In [ ]:
df11

                                            Complaint
0   @AskPayPal Thanks, I have lodged a formal comp...
1   @Cryptogurvy @AskPayPal @PayPal @Dan_Schulman ...
2   @AskPayPal \nHello ,I'm Sean Brennan. \nI file...
3   @AskPayPal How can I complain about customer s...
4   @AskPayPal @PayPal - COMPLAINT - Rubbish websi...
5   @AskPayPal hello, im not able to receive my pa...
6   @PayPal you have just failed an order yet take...
7   @AskPayPal Why you are ignoring the the SMS is...
8   @AskPayPal I have the funds on my card for my ...
9   @paypal @AskPayPal Shipstation is terrible.  C...
10  @PayPalUK @AskPayPal When paying via mobile br...
11  I’m going to stop using @PayPal terrible custo...
12  Going to stop using @PayPal unreliable, very e...
13  @TheFlourishing8 @AskPayPal The service is sti...
14  @AskPayPal I have been trying to activate my r...
15  @AskPayPal phone customer service has been hor...
16  @AskPayPal you should see this stream. The @Pa...
17  @AskPayPal My email address is irrelevant and ...
18  Anyone else have the problem where paypal hold...
19  @PayPal @AskPayPal Why would you change the wa...
20  @sam_penniston @facebookapp @AskPayPal Oh sorr...
21  @PayPal why is your website so bad and why is ...
22  @SiaSynn @PayPal @AskPayPal Support services s...
23  Why is PayPal support so fucking bad? These gu...
24  @JuniorMajeed2 @AskPayPal @PayPal it's long ov...
25  @AskPayPal how long will i wait for the email?...
26  Out $1800! Attempted to send a buddy his fanta...
27  @AskPayPal trying to submit an appeal in regar...
28  @AskPayPal I can’t get into my account.. it ke...
29  @AskPayPal you’ve got the wrong number for ver...
30  @AskPayPal Beware of these Scammers!! They are...
31  still nothing now i have to wait all weekend w...
32  MSME's please make sure that you do not take i...
33  @AskPayPal I have been trying to activate my r...
34  @AskPayPal I want #NOTHING from your woke comm...
35  @AskPayPal  plz close wrong claim and support ...
36  @AskPayPal @PayPal @PayPal4Business \n\nWhat's...
37  @AskPayPal Y'all don't care, highkey doubt thi...
38  WTF is wrong with you? @PayPal  @AskPayPal @Pa...
39  So apparently my signed sour art card is going...
40  @AskPayPal I got my cpf wrong on my account, h...

In [ ]:
qqq11 = ['@VenmoSupport complaint','@VenmoSupport failure', '@VenmoSupport failed', '@VenmoSupport terrible', '@VenmoSupport horrible', '@VenmoSupport bad', '@VenmoSupport wrong']

In [ ]:
lis12 = []
for i in qqq11:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis12.append(tweet.full_text)

In [ ]:
df12 = pd.DataFrame(lis12, columns = ['Complaint'])
df12.to_csv('venmo.csv')

In [ ]:
df12

                                           Complaint
0  @KwitFollowingMe @2022_Karma @Venmo @VenmoSupp...
1  @TimespaceC @2022_Karma @Venmo @VenmoSupport I...
2  @2022_Karma @Venmo @VenmoSupport .@Venmo has b...
3  @VenmoSupport Neither my nor my mother's accou...
4  Just so EVERYONE is aware: whomever designed t...

In [ ]:
qqq12 = ['@Razorpay complaint','@Razorpay failure', '@Razorpay failed', '@Razorpay terrible', '@Razorpay horrible', '@Razorpay bad', '@Razorpay wrong']

In [ ]:
lis13 = []
for i in qqq12:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis13.append(tweet.full_text)

In [ ]:
df13 = pd.DataFrame(lis13, columns = ['Complaint'])
df13.to_csv('raxorpay.csv')

In [ ]:
df13

                                            Complaint
0   @Razorpay @RazorpayCare Hello! I Had Raised a ...
1   @RazorpayCare @Razorpay \nticket ID:4455246\nw...
2   @Razorpay @RazorpayCare\nMy ticket no. 4557888...
3   Thanks @RBI\n Based on your response, the comp...
4   @RBI please let me know how to raise complaint...
5   through, they refuse to issue a refund or deli...
6   @Razorpay @RazorpayCare\nMy ticket no. 4455246...
7   @RazorpayCare @Razorpay\nMy ticket no. 4537334...
8   @pratyus5 @_chiragdoshi @Razorpay @police_hary...
9   @Razorpay ticket #4488439 the merchant LAdy st...
10  @ashisharchitect @Dinesh3018 @Razorpay DIGITAL...
11  @Razorpay My payment was failed to merchant I ...
12  @Paytm @Razorpay @RazorpayCare @RBI  Paytm and...
13  @Lazy_Pay My @phablecare transaction  was fail...
14  @Razorpay team my payment was failed 3-4 days ...
15  Hey @Razorpay, yesterday at 4.13pm i made an U...
16  @Razorpay sir i have a transaction by paytm on...
17  @Razorpay @RazorpayCare  your payment gateway ...
18  @Razorpay it's been 5 days since I have reques...
19  @Razorpay I did shopping in Bosch stores with ...
20  @Razorpay Sir I was applying the form of Pandi...
21  @DodiyaRaviR @Razorpay @PMOIndia @FinMinIndia ...
22  @twitabhinandan @RBI @Razorpay @KotakCares @ja...
23  @Razorpay Don't use Razorpy very very poor ser...
24  Hello @harshilmathur which kind of service you...
25  @RazorpayCare @Razorpay \nSir there is a fraud...
26  @Razorpay ur reply submitted in my personal me...
27  @Razorpay Need to report a dispute transaction...

In [ ]:
qqq11 = ['@YESBANK no response',
               '@TheOfficialSBI no response',
               '@ICICIBank_Care no response',   '@financialombuds no response', '@GooglePayIndia no response',
               '@bankofbaroda no response',
               '@MyIndusIndBank no response',
               '@pnbindia no response',
               '@HDFCBank_Cares no response',
               '@RBIsays no response',
               '@PhonePeSupport no response',
               '@Paytmcare no response',
              '@AmazonHelp no response',
              '@AskCiti no response', '@BofA_Help no response'
      '@RBS_Help no response', '@BarclaysUKHelp no response', 
 '@Ask_WellsFargo no response', '@ChaseSupport no response', '@AskUSBank no response']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis12 = []
for i in qqq11:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis12.append(tweet.full_text)

In [ ]:
df12 = pd.DataFrame(lis12, columns = ['Complaint'])
df12.to_csv('customerserv4.csv')

In [ ]:
df12

                                             Complaint
0    @YESBANK No response and resolution yet.\n\nIs...
1    @YESBANK No one contacted me to get this initi...
2    @YESBANK dear team, \nI want to increase the l...
3    Amount debited from my saving account but not ...
4        @YESBANK No response from your side till now.
..                                                 ...
668  @ChaseSupport good morning, I messaged custome...
669          @ChaseSupport Hours later, no response. 🗑
670  @ChaseSupport Same robotic response to everyon...
671  @ChaseSupport I DM’d you 10 mins ago, no respo...
672  7 rings when I call my local @Chase branch, no...

[673 rows x 1 columns]

In [ ]:
qqq13 = ['@YESBANK interest rate',
               '@TheOfficialSBI interest rate',
               '@ICICIBank_Care interest rate',   '@financialombuds interest rate', '@GooglePayIndia interest rate',
               '@bankofbaroda interest rate',
               '@MyIndusIndBank interest rate',
               '@pnbindia interest rate',
               '@HDFCBank_Cares interest rate',
               '@RBIsays interest rate',
               '@PhonePeSupport interest rate',
               '@Paytmcare interest rate',
              '@AmazonHelp interest rate',
              '@AskCiti interest rate', '@BofA_Help interest rate'
      '@RBS_Help interest rate', '@BarclaysUKHelp interest rate', 
 '@Ask_WellsFargo interest rate', '@ChaseSupport interest rate', '@AskUSBank interest rate']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis14 = []
for i in qqq13:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis14.append(tweet.full_text)

In [ ]:
df14 = pd.DataFrame(lis14, columns = ['Complaint'])
df14.to_csv('interest2.csv')

In [ ]:
df14

In [ ]:
qqq14 = ['ApplePay good service', 'ApplePay great service', 'ApplePay smooth','ApplePay successful', 'applepay best', 'applepay satisfactory', 'applepay good features','applepay great features', 'ApplePay good feature','ApplePay great feature','ApplePay new features','ApplePay new features','ApplePay good offer','ApplePay great offer']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis15 = []
for i in qqq14:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis15.append(tweet.full_text)

In [ ]:
df15 = pd.DataFrame(lis15, columns = ['Complaint'])
df15.to_csv('applepay.csv')

In [ ]:
df15

                                           Complaint
0  - Deposit $10 - $15,000 with A 25% Bonus Added...
1  @FestivalG20 I think it’s a great service. Was...
2  @MetaMaskSupport hi! Are there certain types o...
3  @whalesonly1 Simplest for smaller bags in Aust...
4  Macbeth being the best movie of 2922 #Macbeth ...
5  #XboxSeriesX bundles live now. ApplePay works ...
6  If you have ApplePay like me, you can select y...
7  We are still facing issues on IOS, but rest as...
8  @lazutkinandrew @Tangem You'll have the best p...
9  11\\nAnother great feature that $SCC has put i...

In [ ]:
qqq15 = ['@UCOBankCare complaint', '@UCOBankCare fail','@UCOBankCare bad', '@UCOBankCare horrible','@UCOBankCare terrible', '@UCOBankCare fraud','@UCOBankCare issue', '@UCOBankCare atm', '@UCOBankCare transaction']

# ['@ICICIBank_Care transaction' ,
#        '@HDFCBank_Cares transaction', '@AskCiti transaction', '@BofA_Help transaction'
#       '@RBS_Help transaction', '@BarclaysUKHelp transaction', '@Ask_WellsFargo transaction', '@ChaseSupport transaction', '@AskUSBank transaction']

In [ ]:
lis16 = []
for i in qqq15:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis16.append(tweet.full_text)

In [ ]:
df16 = pd.DataFrame(lis16, columns = ['Complaint'])
df16.to_csv('uco.csv')

In [ ]:
df16

                                           Complaint
0  Without any enquiries uco banking close the co...
1  @UCOBankCare  unhappy with the service and on ...
2  @UCOBankOfficial Link fail is the common probl...
3  My 2nd account is not visible in Internet bank...
4  @UCOBankOfficial @UCOBankCare  I had done a tr...
5  @UCOBankOfficial Kindly activate ur net bankin...
6  Just Blank Screen... @UCOBankOfficial @UCOBANK...
7  @UCOBankOfficial @UCOBankCare @UCOBANKHO unabl...
8  “Sorry State of Affairs”\n\nWasn’t able to do ...

In [ ]:
qqq15 = ['@flipkartsupport transaction fail', '@flipkartsupport payment fail', '@flipkartsupport money fraud', '@flipkartsupport pay fraud', '@flipkartsupport pay fail']

In [ ]:
lis16 = []
for i in qqq15:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis16.append(tweet.full_text)

In [ ]:
df16 = pd.DataFrame(lis16, columns = ['Complaint'])
df16.to_csv('transflip2.csv')

In [ ]:
df16

                                             Complaint
0    @flipkartsupport After continuous persuasion f...
1    @amazonhelp @nch14404 @jagograhakjago @Consumr...
2    @Flipkart  Your company is doing Fraud. Took m...
3    @AmazonHelp @jagograhakjago @nch14404 @flipkar...
4    @flipkartsupport Ohh, thanks for explaining th...
..                                                 ...
125  @sushmanish @Cyberdost @woohoogifting @Flipkar...
126  @Gyan1008Jain @Cyberdost @woohoogifting @Flipk...
127  @flipkartsupport @flipkartsupport which I'll p...
128  Firstly, wrong items were sent from @Flipkart,...
129  @Flipkart @flipkartsupport @ask_AXIS @AxisBank...

[130 rows x 1 columns]

In [ ]:
qqq15 = ['worst refund policies', 'terrible refund policies', 'complaint refund policies', 'complain refund policies', 'refund policies unsatifactory', 'refund policies issue','worst refund policy', 'terrible refund policy', 'complaint refund policy', 'complain refund policy', 'refund policy unsatifactory', 'refund policy issue']

In [ ]:
lis16 = []
for i in qqq15:
    for tweet in tweepy.Cursor(api.search, q=i, tweet_mode="extended").items(1000):
        if (not tweet.retweeted) and 'RT @' not in tweet.full_text:
            lis16.append(tweet.full_text)

In [ ]:
df16 = pd.DataFrame(lis16, columns = ['Complaint'])
df16.to_csv('crp.csv')

In [ ]:
df16

                                             Complaint
0    @PlaystationCAN worst customer service policie...
1    #attention @Frontierair1  @bbb_us Frontier Air...
2    @oyorooms Worst customer service .. not stayed...
3    @RookieRiderYT Only 2 months left, but a pain ...
4    @OliverDlouhy https://t.co/m5uglCWSlD has wors...
..                                                 ...
118  @hmty0 @ChhuganiAshok @maxbhi If there is any ...
119  And when I called tata sky customer care for t...
120  @policybazaar I haven’t heard back from your t...
121  @myntra @MyntraSupport I'm facing refund issue...
122  @AJIOLife @VyshnaviiiG This I have been listen...

[123 rows x 1 columns]